# Generated by Django 2.1.7 on 2019-04-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='name',
            field=models.TextField(default='SNKEY'),
        ),
    ]
